### ISSUE TITLE
mint non functional on hyprland

### ISSUE THREAD

**Issue by toxicfox2491** [trumank/mint#247] opened 2024-10-10 17:14 UTC
I dont know how to word the title better but mint doesnt work on hyprland
if you need any more info from me ask :3
the log file doesnt seem to have alot of info but I'll send it anyways

[drg-mod-integration.log](https://github.com/user-attachments/files/17331798/drg-mod-integration.log)
![Screenshot_10-Oct_19-08-52_17879](https://github.com/user-attachments/assets/b9a1ff40-8f04-4c3a-a74a-9ea3ad6e0cd5)
![swappy-20241010-190937](https://github.com/user-attachments/assets/8ecacf5f-d7aa-4a90-96c9-0c1d183dd097)

**Comment by hollowstrawberry** [comment] 2024-10-12 21:26
can confirm

**Comment by toxicfox2491** [comment] 2024-10-12 23:42
> can confirm
after a bit of talking on discord someone told me I can fix this by launching it in the terminal with `env -u WAYLAND_DISPLAY ./drg_mod_integration`
![image](https://github.com/user-attachments/assets/9f295073-8095-4f40-ae77-96e18f080aeb)
I dont know if I should close the issue or not 
but it does work setting the env

**Comment by sylvercritter** [comment] 2024-10-24 03:53
duplicate of #184

**Closed** 2024-10-24 11:24 UTC
