### ISSUE TITLE
connection time out when install mods

### ISSUE THREAD

**Issue by LeoBlackMT** [trumank/mint#244] opened 2024-09-23 15:47 UTC
i imported my mods then clicked the install mods button , after some minutes it seems that i can't connect to the discord cdn
i try to access the url but it shows "this content is no longer available."

log:
ERROR drg_mod_integration::gui::message: ureq error: https://cdn.discordapp.com/attachments/817251677086285848/992648087371792404/oo2core_9_win64.dll: Connection Failed: Connect error: connection timed out
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: BaseThreadInitThunk

**Comment by trumank** [comment] 2024-09-23 16:01
Duplicate of https://github.com/trumank/mint/issues/134

**Closed by trumank** 2024-09-23 16:01 UTC
