### ISSUE TITLE
MINT Incompatibility (ver. 0.2.10)

### ISSUE THREAD

**Issue by Exophyz** [trumank/mint#262] opened 2024-12-08 03:16 UTC
Due to an undocumented issue which forced a user to use older MINT (game would crash on load when running ver. 0.2.10), it has been discovered that 0.2.10 release causes a new incompatibility issue.

When using MINT ver. 0.2.9, as client and trying to connect to a host using 0.2.10, "Multiplayer Session Ended" will appear, and the client will fail to connect.

This issue has been recorded as only being seen when the host is using the latest MINT, and does not occur when the host runs previous versions of MINT, even when the client is using 0.2.10.

Please contact me at coilgunner2 on Discord if help is needed replicating the issue.

**Comment by trumank** [comment] 2024-12-08 03:50
Duplicate of #79. Compatibility between versions should not be expected. If there is an issue preventing the latest version from being used, that should be reported as an issue so it can be fixed.

**Closed by trumank** 2024-12-08 03:50 UTC
