### ISSUE TITLE
Game freeses on loading screen after clicking continue when launching the game

### ISSUE THREAD

**Issue by LolTape** [trumank/mint#221] opened 2024-06-30 18:22 UTC
Game freezes on loading screen after clicking continue when launching the game and stops responding

these are the mods 
https://mod.io/g/drg/m/refinery-pipe-qol#4050930
https://mod.io/g/drg/m/steeve-better-visibility#1585858
https://mod.io/g/drg/m/missioncontrol-icon-for-yuuka#2863380
https://mod.io/g/drg/m/pink-sugar#2463053
https://mod.io/g/drg/m/drglib#1034237
https://mod.io/g/drg/m/mod-hub#1792770
https://mod.io/g/drg/m/blue-archive-ai-yuuka-voice-pack#2809923
https://mod.io/g/drg/m/motd-stattrack#1145532
https://mod.io/g/drg/m/rancors-rig-hud#1769472
https://mod.io/g/drg/m/weapon-heat-crosshair#1634437
https://mod.io/g/drg/m/ammo-percentage-indicator-e#2671319
https://mod.io/g/drg/m/promotion-levels-after-legendary-3-indicator#2369777
https://mod.io/g/drg/m/fast-forging-continued#3350207
https://mod.io/g/drg/m/shout-framework#2751974
https://mod.io/g/drg/m/11037#3294545
https://mod.io/g/drg/m/a-better-modding-menu#2247462
https://mod.io/g/drg/m/anime-character-icons-v2#2973177
https://mod.io/g/drg/m/trigger-happy-havoc#2843369
https://mod.io/g/drg/m/platform-placement-preview#1674997
https://mod.io/g/drg/m/capoo-lootbug#2982771
https://mod.io/g/drg/m/much-better-flares#1485214

**Comment by trumank** [comment] 2024-06-30 18:38
Duplicate of #44

**Closed by trumank** 2024-06-30 18:38 UTC
