### ISSUE TITLE
The Binary does not execute on void linux

### ISSUE THREAD

**Issue by japjao** [trumank/mint#220] opened 2024-06-30 14:32 UTC
Executing the binary in the terminal results in this error
```
interface 'wl_surface' has no event 2
thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glutin-0.30.10/src/api/egl/surface.rs:239:44:
called `Option::unwrap()` on a `None` value
```
apologies if i have not provided enough information, i would be happy to give more in request

**Comment by trumank** [comment] 2024-06-30 16:14
Duplicate of #220

**Closed by trumank** 2024-06-30 16:14 UTC
