### ISSUE TITLE
Does not run on Steam Deck

### ISSUE THREAD

**Issue by slice-the-idiot** [trumank/mint#242] opened 2024-09-14 00:04 UTC
when i try running the program through desktop or game mode, i get nothing, while when i open it through konsole, i get this
` error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

**Comment by Saigaiii** [comment] 2024-09-20 00:04
Yup I had this issue as well. Never found a fix. Even running the windows version under wine brings up an error when trying to put the api token with a:

"tcp connect error: OS Error 10051 (FormatMessagew() returned error 317) (os error 10051)"

**Comment by trumank** [comment] 2024-09-23 16:02
Duplicate of https://github.com/trumank/mint/issues/122

**Closed by trumank** 2024-09-23 16:02 UTC
